spring:
  application:
    name: webBH

  # Config Redis dùng xử lý access Token, refresh token
  data:
    redis:
      host: redis-17551.c238.us-central1-2.gce.cloud.redislabs.com
      port: 17551
      username: default
      password: TJubwZNfixw8GSmOsHY6zLAxXGtM26da
      # Tắt SSL đối với bản Free của Redis Labs
      ssl:
        enabled: false
      timeout: 50000 # Tăng lên 5 giây để tránh đứt kết nối

  # Config JDBC
  datasource:
    url: "jdbc:postgresql://ep-flat-bird-a8we88wk-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
    username: neondb_owner
    password: npg_6bSNFG2QKdhZ
    driverClassName: org.postgresql.Driver

  # Config JPA
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+7
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  # Config Mail (Đã đưa ra ngoài ngang hàng với jpa, datasource)
  mail:
    host: smtp.gmail.com
    port: 587
    username: vohuuphuoc1102@gmail.com
    password: pphj mujp djgn jdre
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Config Swagger (Đưa hẳn ra ngoài cùng, không thuộc spring)
springdoc:
  swagger-ui:
    path: /webanhang.html  # Đã sửa lỗi chính tả parth -> path
    operationsSorter: method